[versions]
agp = "8.10.1"
androidGifDrawable = "1.2.25"
androidxCredentials = "1.3.0"
cardview = "1.0.0"
circleimageview = "3.1.0"
coordinatorlayout = "1.3.0"
coreKtx = "1.15.0"
credentials = "1.5.0-beta01"
credentialsPlayServicesAuth = "1.3.0"
credentialsVersion = "1.2.0-alpha01"
firebaseBom = "33.7.0"
firebaseDatabase = "21.0.0"
firebaseFirestore = "25.1.1"
firebaseMessaging = "24.1.1"
glide = "4.15.1"
googleFirebaseAuth = "22.1.2"
googleid = "1.1.1"
gradle = "16.0.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
lottie = "5.2.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
materialVersion = "1.9.0"
navigationFragment = "2.6.0"
navigationFragmentKtx = "2.8.5"
navigationFragmentKtxVersion = "2.8.5"
navigationUi = "2.6.0"
navigationUiKtx = "2.8.5"
navigationUiKtxVersion = "2.7.1"
okhttp = "4.12.0"
playServicesAuth = "21.3.0"
playServicesAuthVersion = "20.7.0"
roomRuntime = "2.6.1"
firebaseAuth = "23.1.0"
annotation = "1.6.0"
lifecycleLivedataKtx = "2.6.1"
lifecycleViewmodelKtx = "2.6.1"
swiperefreshlayout = "1.2.0-beta01"
viewpager2 = "1.1.0"
youtubeAndroidPlayerApi = "1.2.2"
roomCommon = "2.6.1"
appcompatVersion = "1.7.1"

[libraries]
android-gif-drawable = { module = "pl.droidsonroids.gif:android-gif-drawable", version.ref = "androidGifDrawable" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
credentials-play-services-auth-v130 = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
credentials-v120alpha01 = { module = "androidx.credentials:credentials", version.ref = "credentialsVersion" }
credentials-v130 = { module = "androidx.credentials:credentials", version.ref = "androidxCredentials" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-database = { module = "com.google.firebase:firebase-database", version.ref = "firebaseDatabase" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebaseFirestore" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-firebase-auth-v2212 = { module = "com.google.firebase:firebase-auth", version.ref = "googleFirebaseAuth" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
gradle = { module = "com.chaquo.python:gradle", version.ref = "gradle" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v190 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
navigation-fragment-ktx-v271 = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtxVersion" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
navigation-ui-ktx-v271 = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtxVersion" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
play-services-auth-v2070 = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuthVersion" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
room-paging = { module = "androidx.room:room-paging", version.ref = "roomRuntime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
room-rxjava2 = { module = "androidx.room:room-rxjava2", version.ref = "roomRuntime" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
youtube-android-player-api = { module = "com.google.android.youtube:youtube-android-player-api", version.ref = "youtubeAndroidPlayerApi" }
room-common = { group = "androidx.room", name = "room-common", version.ref = "roomCommon" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompatVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

